user: "LucasVbr"

socials:
  - name: "Portfolio"
    url: "https://www.lucasvbr.dev"

  - name: "Linkedin"
    url: "https://www.linkedin.com/in/lucasvbr"

  - name: "FreeCodeCamp"
    url: "https://www.freecodecamp.org/LucasVbr"

  - name: "OpenClassRooms"
    url: "https://openclassrooms.com/fr/members/97j9zltv6225"

  - name: "Exercism"
    url: "https://exercism.org/profiles/LucasVbr"

skills:
  - Android
  - Angular
  - Astro
  - Bun
  - Bootstrap
  - Bulma
  - C
  - CSS3
  - Deno
  - Docker
  - Express
  - Figma
  - Git
  - GNU Bash
  - HTML5
  - JavaScript
  - MariaDB
  - MongoDB
  - MySQL
  - Node.js
  - OCaml
  - PHP
  - PostgreSQL
  - Pug
  - Python
  - React
  - SQLite
  - Symfony
  - TypeScript