author:
  first_name: Lucàs
  location: 🇫🇷 Toulouse, France
  company: UPPA
socials:
  - name: Portfolio
    icon: https://img.shields.io/static/v1?message=Portfolio&label=&color=000&labelColor=&style=for-the-badge
    url: https://www.lucasvbr.dev
  - name: LinkedIn
    icon: https://img.shields.io/static/v1?message=LinkedIn&logo=linkedin&label=&color=0077B5&logoColor=white&labelColor=&style=for-the-badge
    url: https://www.linkedin.com/in/lucasvbr
skills:
  - name: Astro
    icon: https://skillicons.dev/icons?i=astro
  - name: Bun
    icon: https://skillicons.dev/icons?i=bun
  - name: Docker
    icon: https://skillicons.dev/icons?i=docker
  - name: Git
    icon: https://skillicons.dev/icons?i=git
  - name: OCaml
    icon: https://skillicons.dev/icons?i=ocaml
  - name: PHP
    icon: https://skillicons.dev/icons?i=php
  - name: Python
    icon: https://skillicons.dev/icons?i=py
  - name: React
    icon: https://skillicons.dev/icons?i=react
  - name: Symfony
    icon: https://skillicons.dev/icons?i=symfony
  - name: TypeScript
    icon: https://skillicons.dev/icons?i=ts
