name: Generate README and Deploy to Main

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run README generator
        run: bun run build

      - name: Commit to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Stash le README généré
          git stash push -m "generated-readme" README.md

          # Switch vers main
          git checkout main

          # Appliquer le README généré depuis le stash
          git stash pop

          # Commit si nécessaire
          git add README.md
          git commit -m "chore: update README [auto]" || echo "No changes to commit"
          git push origin main
          git add README.md
          git commit -m "chore: update README [auto]"
          git push origin main
