name: Generate README and Deploy to Main

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run README generator
        run: bun run build

      - name: Commit to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Sauvegarde le README généré
          cp README.md /tmp/generated-readme.md

          # Supprime le fichier local non suivi pour pouvoir changer de branche
          rm README.md

          # Change de branche
          git checkout main

          # Remet le README généré dans la branche main
          cp /tmp/generated-readme.md README.md

          # Commit & push
          git add README.md
          git commit -m "chore: update README [auto]" || echo "No changes to commit"
          git push origin main
